In [23]:
# 라이브러리 사용
import pandas as pd
import tensorflow as tf

### 보스턴 집값 예측

In [24]:
# 1.과거의 데이터를 준비합니다.
파일경로 = './csv/boston.csv'
보스톤 = pd.read_csv(파일경로)
# 칼럼이름 출력
print(보스톤.columns)

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


In [25]:
# 독립변수, 종속변수
독립 = 보스톤[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 보스톤[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [26]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[13]) # 13개 input
H = tf.keras.layers.Dense(10, activation='swish')(X) # hidden layer의 활성화 함수 swish를 사용. 10개의 노드를 사용
Y = tf.keras.layers.Dense(1)(H) # 1개의 ouput. 출력층은 H를 받아서 만듬
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [7]:
# 모델 구조 확인
model.summary()
'''
입력층은 13개 입력을 받은 다음에 두번재 층은 13개의 입력을 받아서 10개의 output을 만드는 layer를 추가했죠.
마지막 출력층은 10개 입력을 받아서 1개의 출력을 만드는 layer를 추가했습니다.
해석해 보면 우리가 기대했던 모델과 동일한 모델인지 확인할 수 있어요. 오른쪽의 파라미터는 컴퓨터 학습하는 가중치 개수입니다.
마지막 출력층은 10개 입력을 받아서 1개의 출력을 만드니까 수식항이 10개에 bisa가 1개로 11개 가중치를 찾게 되죠. 그래서 11개 
가중치라고 나오고, 10개를 만드는데는 수식이 10개죠. 10개의 출력을 만드는 것이니까 입력이 13개이니 항 13개, bias 1개 해서 
14개 수식마다 14개의 가중치가 필요합니다. 14 X 10 을 해서, 140개의 가중치를 찾는 다고 해석이 되는 것입니다. 
이렇게 summary를 해보시면 내가 만든 모델의 모양을 해석해 보실수 있습니다.
'''

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)             │ (None, 13)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 10)                  │             140 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │              11 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 151 (604.00 B)

 Trainable params: 151 (604.00 B)

 Non-trainable params: 0 (0.00 B)

In [27]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)

In [14]:
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - loss: 23.6302
Epoch 2/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 773us/step - loss: 25.2138
Epoch 3/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - loss: 28.2576
Epoch 4/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 776us/step - loss: 23.7926
Epoch 5/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 756us/step - loss: 29.0700
Epoch 6/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - loss: 21.6551
Epoch 7/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - loss: 28.9412
Epoch 8/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 800us/step - loss: 22.7763
Epoch 9/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 789us/step - loss: 26.5433
Epoch 10/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 727us/step - loss: 28.7456


In [15]:
# 4.모델을 이용합니다.
print(model.predict(독립[:5])) # 예측
print(종속[:5])  # 실제 정답

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
[[29.979324]
 [24.569754]
 [30.990198]
 [29.95444 ]
 [29.429163]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


#### 아이리스 품종 분류

In [16]:
# 1.과거의 데이터를 준비합니다.
파일경로 = './csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

# 원핫인코딩
인코딩 = pd.get_dummies(아이리스)

# 독립변수, 종속변수
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [17]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4]) 
H = tf.keras.layers.Dense(8, activation='swish')(X)  # 히든레이어 추가. 8개의 ouput
H = tf.keras.layers.Dense(8, activation='swish')(H)  # 히든레이어 추가. 8개의 ouput
H = tf.keras.layers.Dense(8, activation='swish')(H)  # 히든레이어 추가. 8개의 ouput
Y = tf.keras.layers.Dense(3, activation='softmax')(H) 
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', 
              metrics = ['accuracy'])

In [18]:
model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)           │ (None, 4)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 8)                   │              40 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 8)                   │              72 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 8)                   │              72 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 3)                   │              27 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 211 (844.00 B)

 Trainable params: 211 (844.00 B)

 Non-trainable params: 0 (0.00 B)

In [19]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=100, verbose=0)

In [20]:
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9764 - loss: 0.1435 
Epoch 2/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9864 - loss: 0.1334 
Epoch 3/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9755 - loss: 0.1472 
Epoch 4/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9651 - loss: 0.1508 
Epoch 5/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9851 - loss: 0.1321 
Epoch 6/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9768 - loss: 0.1399 
Epoch 7/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9738 - loss: 0.1412 
Epoch 8/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9711 - loss: 0.1297 
Epoch 9/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9807 - loss: 0.1226 
Epoch 10/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9860 - loss: 0.1322 


In [21]:
# 4.모델을 이용합니다.
print(model.predict(독립[:5])) # 예측
print(종속[:5])  # 실제 정답

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
[[9.9661416e-01 7.2081736e-04 2.6650794e-03]
 [9.9542266e-01 1.0614054e-03 3.5158989e-03]
 [9.9551398e-01 1.0348557e-03 3.4511806e-03]
 [9.9477369e-01 1.2602616e-03 3.9661187e-03]
 [9.9655223e-01 7.4059557e-04 2.7071792e-03]]
   품종_setosa  품종_versicolor  품종_virginica
0       True          False         False
1       True          False         False
2       True          False         False
3       True          False         False
4       True          False         False


In [ ]:
# 맨 끝 데이터 5개
print(model.predict(독립[-5:]))
print(종속[-5:])  # 실제 정답

그전에 모델보다 학습된 결과가 많이 차이가 나는 것을 확인할 수 있습니다. 딥러닝 모델의 수업은 끝입니다.